
{
    "name": "Tienda Nube - Odoo Connector",
    "summary": """
        Conector de Tienda Nube con Odoo""",
    "category": "Sale",
    "version": "19.0.0.0.4",
    "website": "https://devoo.io",
    "author": "Iván Arriola | Valentin Romero - Devoo",
    "license": "LGPL-3",
    "depends": [
        "base",
        "stock",
        "sale_management",
    ],
    "data": [
        "data/product_discount_tn.xml",
        "data/cron_update_stock_tn.xml",
        "data/product_template_actions.xml",
        "data/cron_update_product_price.xml",
        "data/cron_sync_orders_today_tn.xml",
        "data/product_shipping_tn.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/multi_company_rules.xml",
        "wizards/create_all_products_odoo_views.xml",
        "wizards/create_all_category_odoo_views.xml",
        "wizards/create_all_webhook_odoo_views.xml",
        "wizards/create_all_coupon_odoo_views.xml",
        "wizards/create_all_order_odoo_views.xml",
        "wizards/create_orders_by_date_wizard_views.xml",
        "wizards/get_tn_location_wizard_views.xml",
        "wizards/synchronize_products_wizard_view.xml",
        "wizards/mass_synchronize_products_wizard_view.xml",
        "views/webhook_tn_view.xml",
        "views/res_company_inherit_view.xml",
        "views/menu_view.xml",
        "views/product_template_inherit_view.xml",
        "views/product_product_inherit_view.xml",
        "views/category_tn_view.xml",
        "views/sale_order_inherit_view.xml",
        "views/tn_log_views.xml",
        "views/coupon_tn_views.xml",
        "views/stock_warehouse_inherit_views.xml",
        "views/product_image_tn_view.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'odoo_tienda_nube/static/src/css/mass_sync_wizard.css',
            'odoo_tienda_nube/static/src/scss/website_tn_backend.scss',
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
